### ISSUE TITLE
UI too small to work on high DPI screen

### ISSUE THREAD

**Issue by cacois** [balsamiq/balsamiq-wireframes-linux#8] opened 2021-01-27 14:55 UTC
Pop OS! 20.10

Installed via Lutris 5.8.x.

The entire UI is too small to work with in high DPI. Are there settings anywhere to address this? Here's a screenshot of the balsamiq UI with my browser next to it, so you can see the problem. 

![balsamiq-high-dpi](https://user-images.githubusercontent.com/347087/106008825-f18db180-6074-11eb-94c0-e55a218e1bd2.png)

**Comment by rustybox** [comment] 2021-01-28 08:51
duplicate of #2 and #4

**Comment by cacois** [comment] 2021-01-28 17:03
I looked at those, they seemed to be about blurriness and other visual issues - all the same cause to be sure, though. Feel free to close/merge.

**Comment by fire** [comment] 2022-10-29 05:13
In bottles you can run at 192 dpi and it looks ok.

**Closed** 2023-06-22 14:18 UTC
